apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
  name: nodejs
spec:
  type: NodePort
  ports:
    - port: 8020
      targetPort: 8020
      protocol: TCP
  selector:
    app: nodejs
